# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Archives: /archives
  Tags: /tags
  Catogories: /categories

# stylesheets loaded in the <head>
stylesheets:
  - /css/oasis.css

# scripts loaded in the end of the body
scripts:
  - /js/oasis.js

logo:
  - ./asset/logo.JPG
