# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Archives: /archives
  Tags: /tags

tag_dir: tags
tag_generator:
  per_page: 10
  enable_index_page: true

# stylesheets loaded in the <head>
stylesheets:
  - /css/oasis.css

# scripts loaded in the end of the body
scripts:
  - /js/oasis.js

logo:
  - ./asset/logo.JPG
